#!/bin/bash

for i in `seq 1 3`
do
    java -cp obffrontieres.jar frontieres.ServeurJeu 123$i 1 > logServ$i &
    sleep 1
    java -cp ./bin frontieres.ClientJeu frontieres.JoueurTropFort localhost 123$i > logJ1$i &
    java -cp ./bin frontieres.ClientJeu frontieres.JoueurAlpha localhost 123$i > logJ2$i &
done;
